version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_username
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    networks:
      - shortener
  general-shortener:
    image: merkeg/general-shortener:latest
    restart: always
    ports:
      - 8080:80
    environment:
      MasterToken: master_token
      BaseUrl: http://localhost:8080
      Storage__Path: /tmp
      MongoDB__ConnectionString: mongodb://mongo_username:mongo_password@mongo:27017/
      MongoDB__DatabaseName: general_shortener
    networks:
      - metrics
      - shortener
networks:
  metrics:
    external: true
    name: metrics
  shortener:
