name: Build and push Docker
on:
    release:
        types:
            - created

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build and push to github registry
              id: docker_build
              uses: mr-smithers-excellent/docker-build-push@v5
              with:
                  push: true
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  image: merkeg-general-storage/merkeg-general-storage
